require 'rubygems'
require 'yaml'
require "bundler/setup"
require 'rake/testtask'
require 'pdfkit'
require 'redcarpet'
require 'erb'
require 'tilt'
require 'buttless'

Rake::TestTask.new do |t|
  t.pattern = "test/test_*.rb"
end

desc "Run tests"
task :default => :test

desc "Generate HTML and PDF"
task :gen => [:html, :pdf]

desc "Generate HTML docs"
task :html do
  prepare()
  html = @buttless.generate_html()
  File.open('index.html','w').write(html)
end

desc "Generate PDF docs"
task :pdf => :html do
  # Just print index.html from chrome!
  #`wkhtmltopdf --page-size A4 --margin-left 20mm --margin-right 20mm --margin-top 20mm --margin-bottom 20mm index.html #{@buttless.config["full_title"]}.pdf`
end


def prepare
  root = "#{File.dirname(__FILE__)}"
  b = Buttless.new(root)
  @buttless = b
  @config = b.config
end

def example(name)
  return "TODO" if name.nil?
  name = name.to_s
  File.open("#{@home_dir}/json_examples/#{name}.json".downcase,'r').read()
end